apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - postgres.yaml
  - registry.yaml
  - browser-adversary.yaml
  - company-ops.yaml
  - engineering.yaml
  - postgres-backup.yaml
